import "./globals.css";
import { Rosarivo } from "next/font/google";

const rosarivo = Rosarivo({
  weight: "400",
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className={rosarivo.className}>{children}</body>
    </html>
  );
}
``;
